% Auto-generated by cameraCalibrator app on 28-Nov-2023
%-------------------------------------------------------


% Define images to process
imageFileNames = {'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\1_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\2_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\3_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\4_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\5_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\6_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\7_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\8_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\9_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\10_Color.png',...
    'C:\Users\William\Desktop\Camera_Kalibrierung\Fotos\11_Color.png',...
    };
% Detect calibration pattern in images
detector = vision.calibration.monocular.CheckerboardDetector();
[imagePoints, imagesUsed] = detectPatternPoints(detector, imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Read the first image to obtain image size
originalImage = imread(imageFileNames{1});
[mrows, ncols, ~] = size(originalImage);

% Generate world coordinates for the planar pattern keypoints
squareSize = 30;  % in units of 'millimeters'
worldPoints = generateWorldPoints(detector, 'SquareSize', squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'millimeters', ...
    'InitialIntrinsicMatrix', [], 'InitialRadialDistortion', [], ...
    'ImageSize', [mrows, ncols]);

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams);

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
undistortedImage = undistortImage(originalImage, cameraParams);

% See additional examples of how to use the calibration data.  At the prompt type:
% showdemo('MeasuringPlanarObjectsExample')
% showdemo('StructureFromMotionExample')
